spring.application.name=demo

# ログレベル設定
# =========================================================================
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.org.springframework=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n

# RDB設定
# =========================================================================
spring.datasource.url=jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=2suT5EatVd7gzCD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis設定
# =========================================================================
# MyBatis の自動キャメルケース変換
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.type-aliases-package=com.example.demo.ex0001.entity
