name: CI/CD Spring Boot to ECS

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Set a timestamp environment variable for the build
      - name: Set timestamp
        run: echo "BUILD_TIME=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

# AWS ECR steps
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: login ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build docker image
        run: |
          docker build -t hello-java .

      - name: tag image
        run: |
          docker tag hello-java:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/hello-java:latest

      - name: Push Docker image to ECR
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/hello-java:latest

      - name: Update ECS service
        run: |
          CLUSTER_NAME=hello-cluster
          SERVICE_NAME=hello-java-service
          TASK_NAME=hello-java
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/hello-java:latest

          # タスク定義の現在設定を取得
          TASK_DEF_JSON=$(aws ecs describe-task-definition --task-definition $TASK_NAME)

          # イメージだけ書き換えて新しいタスク定義を登録
          # NEW_TASK_DEF=$(echo $TASK_DEF_JSON | jq --arg IMAGE "$IMAGE_URI" '.taskDefinition | .containerDefinitions[0].image=$IMAGE | {family: .family, containerDefinitions: [.containerDefinitions[0]] }')
          # NEW_TASK_DEF=$(echo $TASK_DEF_JSON | jq --arg IMAGE "$IMAGE_URI" '.taskDefinition | .containerDefinitions[0].image=$IMAGE | {family, containerDefinitions}')
          NEW_TASK_DEF=$(echo "$TASK_DEF_JSON" | jq --arg IMAGE "$IMAGE_URI" '
            .taskDefinition
            | .containerDefinitions[0].image=$IMAGE
            | del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
            )
            ')
          echo "$NEW_TASK_DEF" > new-task.json

          # 新しいタスク定義を登録
          aws ecs register-task-definition --cli-input-json file://new-task.json

          # ECS サービスを更新
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment

# Upload the built JAR file as an artifact for later use
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ github.run_number }}-${{ github.sha }}
          path: target/*.jar        
